name: ci

on:
  push: {}

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write        # required for OIDC
  contents: read

env:
  REGION: us-central1
  PROJECT_ID: single-clock-473907-p6
  AR_REPO: apps
  IMAGE_NAME: hello-gke

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_DEPLOYER_SA }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build & Push image
        run: |
          IMAGE="$REGION-docker.pkg.dev/$PROJECT_ID/$AR_REPO/$IMAGE_NAME:${GITHUB_SHA::7}"
          docker build -t "$IMAGE" ./app
          docker push "$IMAGE"
          echo "IMAGE_URI=$IMAGE" >> $GITHUB_ENV

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials autopilot-lab --region "$REGION" --project "$PROJECT_ID"
          kubectl cluster-info

      - name: Render manifests (swap registry) and apply
        run: |
          REGISTRY_PREFIX="$REGION-docker.pkg.dev/$PROJECT_ID/$AR_REPO"
          sed "s|REGISTRY_PLACEHOLDER|$REGISTRY_PREFIX|g" k8s/deployment.yaml | \
          sed "s|:latest|:${GITHUB_SHA::7}|g" > k8s/deployment.rendered.yaml
          kubectl apply -f k8s/deployment.rendered.yaml
          kubectl apply -f k8s/service.yaml

      - name: Show service EXTERNAL-IP (may take 1-3 min)
        run: kubectl get svc hello -o wide
